// Navigation Menu Items
export const menuItems = [
  { title: "New", link: "/collections/new" },
  { title: "Basics", link: "/collections/basics" },
  {
    title: "Shop",
    link: "#",
    children: [
      { title: "Shop All", link: "/collections/shop-all" },
      { title: "Graphic Tees", link: "/collections/Graphic Tees" },
      { title: "Basic Hoodies", link: "/collections/Basic Hoodies" },
      { title: "Wasteland", link: "/collections/Wasteland" },
      { title: "Basic Tees", link: "/collections/Basic Tees" },
    ],
  },
];
// Navigation Call-To-Actions Items
export const cta = [
  {
  title: "Currencies",
  current: "Nepal",
  code: "NPR",
  symbol: "₨",
  link: "/",
  children: [
    // South Asia
    { title: "Nepal", code: "NPR", symbol: "₨" },
    { title: "India", code: "INR", symbol: "₹" },
    { title: "Pakistan", code: "PKR", symbol: "₨" },
    { title: "Sri Lanka", code: "LKR", symbol: "₨" },

    // North America
    { title: "United States", code: "USD", symbol: "$" },
    { title: "Canada", code: "CAD", symbol: "$" },
    { title: "Mexico", code: "MXN", symbol: "$" },

    // Europe & UK
    { title: "United Kingdom", code: "GBP", symbol: "£" },
    { title: "Europe", code: "EUR", symbol: "€" },
    { title: "Switzerland", code: "CHF", symbol: "CHf" },
    { title: "Sweden", code: "SEK", symbol: "kr" },
    { title: "Norway", code: "NOK", symbol: "kr" },
    { title: "Denmark", code: "DKK", symbol: "kr" },

    // Asia Pacific
    { title: "Japan", code: "JPY", symbol: "¥" },
    { title: "Australia", code: "AUD", symbol: "$" },
    { title: "New Zealand", code: "NZD", symbol: "$" },
    { title: "South Korea", code: "KRW", symbol: "₩" },
    { title: "Singapore", code: "SGD", symbol: "$" },
    { title: "Hong Kong", code: "HKD", symbol: "$" },
    { title: "Thailand", code: "THB", symbol: "฿" },
    { title: "Malaysia", code: "MYR", symbol: "RM" },

    // Middle East & Africa
    { title: "United Arab Emirates", code: "AED", symbol: "د.إ" },
    { title: "Saudi Arabia", code: "SAR", symbol: "﷼" },
    { title: "Qatar", code: "QAR", symbol: "﷼" },
    { title: "South Africa", code: "ZAR", symbol: "R" },

    // South America
    { title: "Brazil", code: "BRL", symbol: "R$" },
    { title: "Argentina", code: "ARS", symbol: "$" },
  ],
},
  { title: "Search", link: "/" },
  // { title: "Login", link: "/" },
  { title: "Cart", link: "#" },
];

import PIC1 from "@/assets/products/pixelcut_1 (1).png"
import PIC2 from "@/assets/products/pixelcut_2 (1).png"
import PIC3 from "@/assets/products/pixelcut_2.png"
import PIC4 from "@/assets/products/pixelcut_3 (1).png"
import PIC5 from "@/assets/products/pixelcut_3.png"
import PIC6 from "@/assets/products/pixelcut_4 (1).png"
import PIC7 from "@/assets/products/pixelcut_4.png"
import PIC8 from "@/assets/products/pixelcut_5 (1).png"
import PIC9 from "@/assets/products/pixelcut_5.png"
import PIC10 from "@/assets/products/pixelcut_6 (1).png"
import PIC11 from "@/assets/products/pixelcut_6.png"
import PIC12 from "@/assets/products/pixelcut_9.png"
import PIC13 from "@/assets/products/pixelcut_10.png"
import PIC14 from "@/assets/products/pixelcut_11.png"
import PIC15 from "@/assets/products/pixelcut_12.png"
import PIC17 from "@/assets/products/pixelcut_14.png"
import PIC18 from "@/assets/products/pixelcut_15.png"
import PIC19 from "@/assets/products/pixelcut_16.png"
import PIC20 from "@/assets/products/pixelcut_17.png"
import PIC21 from "@/assets/products/pixelcut_18.png"
import PIC22 from "@/assets/products/pixelcut_19.png"
import PIC23 from "@/assets/products/pixelcut_8.png"
import PIC24 from "@/assets/products/pixelcut_7.png"
import PIC25 from "@/assets/products/pixelcut_1.png"
import PIC26 from "@/assets/products/brent_faiyaz_white.png"

// Product Items Objects 
export const PRODUCTS_LIST = [
  // --- OUTERWEAR ---
  {
    id: "zy-01",
    title: "Bone Puff",
    slug: "bone-puff",
    category: "Graphic Tees",
    collection: "",
    price: 1250,
    primaryImage: PIC1,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000" }],
    sizes: [ "M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-02",
    title: "SKULL SIREN",
    slug: "skull-siren",
    category: "Graphic Tees",
    price: 1250,
    primaryImage: PIC2,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors:  [{ name: "Black", hex: "#000000" }],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-03",
    title: "TOO LATE TO DIE YOUNG",
    slug: "too-late-to-die-young",
    category: "Graphic Tees",
    collection: "",
    price: 1800,
    primaryImage: PIC3,
    images: [PIC3, PIC17 ],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Vivid", hex: "#875D4C" },{ name: "Static", hex: "#6E6E6E" } ],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-04",
    title: "BRENT FAIYAZ",
    slug: "brent-faiyaz",
    category: "Graphic Tees",
    collection: "",
    price: 1500,
    primaryImage: PIC4,
    images: [PIC4 ,PIC26],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000"} , {name:"White", hex:"#ffffff"}],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-05",
    title: "WASTELAND HOODIE BLACK",
    slug: "wasteland-hoodie-black",
    category: "Wasteland",
    collection: "",
    price: 3500,
    primaryImage: PIC5,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000" }],
    sizes: ["L", "XL"],
    availability: "Limited Release"
  },
  {
    id: "zy-06",
    title: "Tommie",
    slug: "tommie",
    category: "Graphic Tees",
    price: 1500,
    primaryImage: PIC6,
    images: [PIC6 ,PIC8],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000"} , {name:"White", hex:"#ffffff"}],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-07",
    title: "VOID LIPS",
    slug: "void-lips",
    category: "Graphic Tees",
    collection: "",
    price: 1250,
    primaryImage: PIC7,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000"}],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-09",
    title: "Control",
    slug: "control",
    category: "Graphis Tees",
    price: 1500,
    primaryImage: PIC9,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors:[{ name: "Black", hex: "#000000"}],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-10",
    title: "Wasteland Album Cover",
    slug: "wasteland-album-cover",
    category: "Wasteland",
    collection: "",
    price: 1500,
    primaryImage: PIC10,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000" }],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-11",
    title: "Sonder",
    slug: "sonder",
    category: "Graphic Tees",
    collection:"",
    price: 1500,
    primaryImage: PIC11,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "White", hex: "#ffffff" }],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-12",
    title: "THE 'FTW' TEE",
    slug: "the-ftw-tee",
    category: "Essentials",
    price: 1500,
    primaryImage: PIC12,
    images: [PIC12,PIC13],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000" }, { name: "White", hex: "#ffffff" }],
    sizes: ["M", "L" , "XL"],
    availability: "Limited Release"
  },
  {
    id: "zy-14",
    title: "SONDER INTO",
    slug: "sonder-into",
    category: "Graphic Tees",
    collection: "",
    price: 1800,
    primaryImage: PIC14,
    images: [PIC14,PIC15],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [ { name: "White", hex: "#ffffff" },{ name: "Black", hex: "#000000" }],
    sizes: [ "M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-19",
    title: "SONDER SON",
    slug: "sonder-son",
    category: "Graphic Tees",
    price: 2000,
    primaryImage: PIC19,
    images: [PIC19,PIC18],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Maroon", hex: "#9A1319" }, { name: "White", hex: "#ffffff" }],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-20",
    title: "BRENT FAIYAZ V2",
    slug: "brent-faiyaz-v2",
    category: "Graphic Tees",
    price: 1500,
    primaryImage: PIC20,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "White", hex: "#ffffff" }],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-21",
    title: "BRENT STAMP",
    slug: "brent-stamp",
    category: "Graphic Tees",
    price: 1500,
    primaryImage: PIC21,
    images: [PIC21, PIC22],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "White", hex: "#ffffff" }, { name: "Black", hex: "#000000" }],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-24",
    title: "WHAT YOU HEARD",
    slug: "what-you-heard",
    category: "Graphic Tees",
    price: 2000,
    primaryImage: PIC25,
    images: [],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Black", hex: "#000000" }],
    sizes: [ "M", "L", "XL"],
    availability: "In Stock"
  },
  {
    id: "zy-25",
    title: "ONE NIGHT ONLY",
    slug: "one-night-onlt",
    category: "Graphic Tees",
    price: 1800,
    primaryImage: PIC23,
    images: [PIC23,PIC24],
    description: "100% Heavyweight Cotton.Pre-shrunk garment.Tonal embroidery.Boxy, Cropped, Oversized Fit.Made in Nepal | Designed by Zylo Studios.",
    productCare: "Hand wash or machine wash on cold.Hang dry inside or a cool place.Do not use tumble dryer or any type of heat/sun drying.Do not bleach",
    colors: [{ name: "Vivid", hex: "#875D4C" },{ name: "Static", hex: "#6E6E6E" } ],
    sizes: ["M", "L", "XL"],
    availability: "In Stock"
  }
];
// Footer Object
export const FOOTER_LINKS = [
  {
    title: "Help",
    links: [
      { name: "Shipping", href: "/shipping" },
      { name: "Returns", href: "/returns" },
      { name: "FAQs", href: "/faqs" },
      { name: "Terms and Condition", href: "/terms" },
      { name: "Privacy Policy", href: "/policy" },
    ],
  },
  {
    title: "More",
    links: [
      { name: "Contact Us", href: "/contact-us" },
      { name: "New", href: "/collections/new" },
      { name: "Best Seller", href: "/collections/basics" },
      { name: "Shop All", href: "/collections/shop-all" },
    ],
  },
  {
    title: "Socials",
    links: [
      { name: "Instagram", href: "https://www.instagram.com/zylo.studios/" },
    ],
  },
];

// Delivery Location
export const DELIVERY_LOCATIONS = [
  { city: "Bhaktapur", rate: 100 },
  { city: "Godawari", rate: 100 },
  { city: "Kathmandu", rate: 100 },
  { city: "Kirtipur", rate: 100 },
  { city: "Lalitpur", rate: 100 },
  { city: "LubhuLamatar", rate: 100 },
  { city: "Banepa", rate: 150 },
  { city: "Bhairahawa", rate: 140 },
  { city: "Biratnagar", rate: 140 },
  { city: "Butwal", rate: 140 },
  { city: "Dakshinkali", rate: 150 },
  { city: "Dhulikhel", rate: 150 },
  { city: "Itahari", rate: 140 },
  { city: "Kavre", rate: 150 },
  { city: "Lele", rate: 150 },
  { city: "Narayangarh", rate: 135 },
  { city: "Panauti", rate: 150 },
  { city: "Pharphing", rate: 150 },
  { city: "Pokhara", rate: 135 },
  { city: "Sankhu", rate: 150 },
  { city: "Sundarijal", rate: 150 },
  { city: "Thankot", rate: 150 },
  { city: "Bharatpur", rate: 145 },
  { city: "Lekhnath", rate: 145 },
  { city: "Jogikuti", rate: 160 },
  { city: "Birgunj", rate: 160 },
  { city: "Hetauda", rate: 150 },
  { city: "Tandi", rate: 160 },
  { city: "Biratchowk", rate: 170 },
  { city: "Baglung", rate: 180 },
  { city: "Bardibas", rate: 180 },
  { city: "Belbari", rate: 180 },
  { city: "Bhadrapur", rate: 170 },
  { city: "Birtamod", rate: 170 },
  { city: "Charali", rate: 180 },
  { city: "Chormara", rate: 180 },
  { city: "Daldale", rate: 180 },
  { city: "Damak", rate: 170 },
  { city: "Damauli", rate: 180 },
  { city: "Dhalkebar", rate: 180 },
  { city: "Dhangadhi", rate: 180 },
  { city: "Dharan", rate: 170 },
  { city: "Duhabi", rate: 175 },
  { city: "Dumkibas", rate: 180 },
  { city: "Dumre", rate: 180 },
  { city: "Gaidakot", rate: 165 },
  { city: "Ghorahi", rate: 180 },
  { city: "Inaruwa", rate: 175 },
  { city: "Janakpur", rate: 180 },
  { city: "Jhumka", rate: 175 },
  { city: "Kawasoti", rate: 180 },
  { city: "Kohalpur", rate: 170 },
  { city: "Lahan", rate: 180 },
  { city: "Manigram", rate: 175 },
  { city: "Nepalgunj", rate: 170 },
  { city: "Rajbiraj", rate: 180 },
  { city: "Sunwal", rate: 175 },
  { city: "THUTIPIPAL", rate: 175 },
  { city: "Tulsipur", rate: 180 },
  { city: "Urlabari", rate: 175 },
  { city: "Bardaghat", rate: 180 },
  { city: "Tansen", rate: 180 },
  { city: "Attariya", rate: 190 },
  { city: "Beni", rate: 180 },
  { city: "Bhalwari", rate: 190 },
  { city: "Chandragadhi", rate: 180 },
  { city: "Gaurigunj", rate: 180 },
  { city: "Haldibari", rate: 180 },
  { city: "Kakarvitta", rate: 180 },
  { city: "Kalabanjar", rate: 190 },
  { city: "Mourighat", rate: 190 },
  { city: "Nagarkot", rate: 190 },
  { city: "Rangeli", rate: 190 },
  { city: "Sindhuli", rate: 180 },
  { city: "Tamnagar", rate: 175 },
  { city: "Waling", rate: 190 },
  { city: "Arunkhola", rate: 190 },
  { city: "JhapaBaniyani", rate: 190 },
  { city: "Battar", rate: 190 },
  { city: "Bhalubang", rate: 190 },
  { city: "Bidur", rate: 190 },
  { city: "SirahaBishnupur", rate: 190 },
  { city: "BrahmadevBazar", rate: 190 },
  { city: "Budhabare", rate: 180 },
  { city: "DAIJEE", rate: 190 },
  { city: "DhadingBesi", rate: 190 },
  { city: "SirahaDhangadhimai", rate: 190 },
  { city: "Dhulabari", rate: 180 },
  { city: "DolakhaCharikot", rate: 195 },
  { city: "Gaighat", rate: 190 },
  { city: "SarlahiGair", rate: 190 },
  { city: "SirahaGaneshpur", rate: 190 },
  { city: "Garamani", rate: 200 },
  { city: "SarlahiGodaita", rate: 190 },
  { city: "Golbazar", rate: 190 },
  { city: "JhapaGoldhap", rate: 195 },
  { city: "Gorkha", rate: 190 },
  { city: "Gorusinge", rate: 190 },
  { city: "KanchanpurGulariya", rate: 190 },
  { city: "SaptariHanumannagr", rate: 190 },
  { city: "SarlahiHaripur", rate: 190 },
  { city: "Hariwan", rate: 195 },
  { city: "Hemja", rate: 190 },
  { city: "Ilam", rate: 190 },
  { city: "IlamNepaltar", rate: 195 },
  { city: "BaraJeetpur", rate: 190 },
  { city: "KapilbastuJeetpur", rate: 200 },
  { city: "SaptariKadmaha", rate: 190 },
  { city: "SaptariKanchanpur", rate: 190 },
  { city: "KaskiNaudanda", rate: 190 },
  { city: "JhapaKerkha", rate: 200 },
  { city: "Kotihawa", rate: 195 },
  { city: "Kushma", rate: 190 },
  { city: "Lalbandi", rate: 190 },
  { city: "Lamahi", rate: 190 },
  { city: "Laukahi", rate: 195 },
  { city: "Letang", rate: 190 },
  { city: "LumbiniBazar", rate: 195 },
  { city: "Madhumalla", rate: 190 },
  { city: "SaptariMahadeva", rate: 190 },
  { city: "MahendranagarWest", rate: 190 },
  { city: "MahottariGaushala", rate: 195 },
  { city: "Malangwa", rate: 190 },
  { city: "Murgiya", rate: 190 },
  { city: "SunsariNetaChowk", rate: 200 },
  { city: "KapilbastuOdari", rate: 200 },
  { city: "PadamPokhari", rate: 190 },
  { city: "ChitwanPadampur", rate: 195 },
  { city: "PalpaRampur", rate: 190 },
  { city: "ParasiRamgram", rate: 200 },
  { city: "ChitwanParsa", rate: 190 },
  { city: "Pathari", rate: 190 },
  { city: "Pathlaiya", rate: 190 },
  { city: "Putalibazar", rate: 190 },
  { city: "SarlahiPutalichowk", rate: 190 },
  { city: "NawalparasiRajahar", rate: 190 },
  { city: "RatuwamaiSombare", rate: 190 },
  { city: "Sanischare", rate: 190 },
  { city: "Siraha", rate: 190 },
  { city: "SirahaSukhipur", rate: 190 },
  { city: "Surkhet", rate: 190 },
  { city: "Surunga", rate: 190 },
  { city: "Syangja", rate: 190 },
  { city: "SyangjaChapakot", rate: 190 },
  { city: "Taulihawa", rate: 190 },
  { city: "MahottariAurahi", rate: 195 },
  { city: "DhanusaBirendrabazar", rate: 195 },
  { city: "Chanauli", rate: 200 },
  { city: "Dhanusadham", rate: 195 },
  { city: "Gaur", rate: 190 },
  { city: "Gauradaha", rate: 190 },
  { city: "Gulmi", rate: 200 },
  { city: "Jaleshwor", rate: 195 },
  { city: "Kalaiya", rate: 190 },
  { city: "Katari", rate: 200 },
  { city: "Manthali", rate: 195 },
  { city: "Mirchaiya", rate: 190 },
  { city: "NagarainDhanusha", rate: 195 },
  { city: "Nijgadh", rate: 190 },
  { city: "Ramgopalpur", rate: 195 },
  { city: "DhanushaSabaila", rate: 195 },
  { city: "MahottariSamsi", rate: 195 },
  { city: "Simara", rate: 190 },
  { city: "Tamghas", rate: 200 },
  { city: "DhanushaTinkoriya", rate: 195 },
  { city: "Trishuli", rate: 200 },
  { city: "DhanushaYadukuha", rate: 195 },
  { city: "JhapaBeldangi", rate: 190 },
  { city: "Chandrauta", rate: 200 },
  { city: "Chinchu", rate: 200 },
  { city: "Galkot", rate: 205 },
  { city: "Gopigunj", rate: 190 },
  { city: "Kechana", rate: 190 },
  { city: "Lamki", rate: 210 },
  { city: "Laxmipur", rate: 190 },
  { city: "DhanusaMahendranagar", rate: 200 },
  { city: "Amlekhgunj", rate: 190 },
  { city: "KailaliBauniya", rate: 215 },
  { city: "KailaliBhajani", rate: 215 },
  { city: "BhakundeBesiKavre", rate: 215 },
  { city: "Bhurigaun", rate: 215 },
  { city: "Chandranigapur", rate: 215 },
  { city: "KailaliChisapani", rate: 215 },
  { city: "RautahatDamarchowk", rate: 215 },
  { city: "Dudhauli", rate: 215 },
  { city: "Fikkal", rate: 210 },
  { city: "Galyang", rate: 215 },
  { city: "KailaliGodawari", rate: 215 },
  { city: "Gulariya", rate: 215 },
  { city: "KailaliHasuliya", rate: 215 },
  { city: "KanchanpurMahendranagar", rate: 200 },
  { city: "Kapilbastu", rate: 200 },
  { city: "JhapaKhudunabari", rate: 215 },
  { city: "Malekhu", rate: 215 },
  { city: "Pahalbanpur", rate: 215 },
  { city: "Panchkhal", rate: 215 },
  { city: "Phidim", rate: 210 },
  { city: "Rajapur", rate: 215 },
  { city: "RautahatRajdevi", rate: 215 },
  { city: "JhapaRajgadh", rate: 215 },
  { city: "SalyanKhalanga", rate: 215 },
  { city: "Sandhikarka", rate: 215 },
  { city: "ChitwanSauraha", rate: 215 },
  { city: "Sukkhad", rate: 215 },
  { city: "Tikapur", rate: 215 },
  { city: "Abukhaireni", rate: 190 },
  { city: "Baletaxar", rate: 200 },
  { city: "Bandipur", rate: 215 },
  { city: "SarlahiBarathawa", rate: 200 },
  { city: "SaptariBariyapatti", rate: 200 },
  { city: "KanchanpurBeldandi", rate: 200 },
  { city: "Besisahar", rate: 190 },
  { city: "SirahaBhagwanpur", rate: 200 },
  { city: "Bhedatar", rate: 190 },
  { city: "IIlamChulachuli", rate: 200 },
  { city: "RupandehiDhakdai", rate: 200 },
  { city: "Dhankuta", rate: 200 },
  { city: "Dodhara", rate: 200 },
  { city: "Dulegauda", rate: 200 },
  { city: "DangGogali", rate: 200 },
  { city: "NawalparasiHarkapur", rate: 200 },
  { city: "KapilbastuImiliya", rate: 200 },
  { city: "ChitwanJagatpur", rate: 200 },
  { city: "Jhalari", rate: 200 },
  { city: "Jhiljhile", rate: 190 },
  { city: "PanchtharJorpokhari", rate: 200 },
  { city: "Jugedi", rate: 190 },
  { city: "SaptariKalyanpur", rate: 200 },
  { city: "SirahaKalyanpur", rate: 200 },
  { city: "RupandehiKanchiBazar", rate: 200 },
  { city: "Kanepokhari", rate: 190 },
  { city: "Kerabari", rate: 200 },
  { city: "Khaireni", rate: 190 },
  { city: "Khajura", rate: 200 },
  { city: "Lothar", rate: 200 },
  { city: "ChitwanMadi", rate: 200 },
  { city: "KapilbastuMaharajganj", rate: 200 },
  { city: "IlamMangalbare", rate: 200 },
  { city: "Motipur", rate: 190 },
  { city: "Mugling", rate: 200 },
  { city: "Narayanpur", rate: 200 },
  { city: "Pharsatikar", rate: 200 },
  { city: "SaptariPhattepur", rate: 200 },
  { city: "Pokhariya", rate: 200 },
  { city: "Punarbas", rate: 190 },
  { city: "DhankutaRajarani", rate: 200 },
  { city: "Ramailo", rate: 190 },
  { city: "Ranke", rate: 200 },
  { city: "Ridi", rate: 210 },
  { city: "RudrapurHaraiya", rate: 200 },
  { city: "JhapaSharanmati", rate: 200 },
  { city: "JhapaShivagunj", rate: 200 },
  { city: "ShreeAntu", rate: 200 },
  { city: "Sundarbazar", rate: 190 },
  { city: "SyangjaBayarghari", rate: 200 },
  { city: "MahottariTuteshwar", rate: 200 },
  { city: "Bhandara", rate: 225 },
  { city: "Jiri", rate: 230 },
  { city: "Krishnanagar", rate: 210 },
  { city: "Palungtar", rate: 225 },
  { city: "Amuwa", rate: 240 },
  { city: "Bahrabise", rate: 240 },
  { city: "Bahundangi", rate: 240 },
  { city: "Bansagadhi", rate: 240 },
  { city: "Belauri", rate: 250 },
  { city: "Beltar", rate: 240 },
  { city: "SunsariBhantabari", rate: 240 },
  { city: "Bhimad", rate: 210 },
  { city: "SindhuliBhiman", rate: 240 },
  { city: "SaptariBodebarsain", rate: 200 },
  { city: "Burtibang", rate: 240 },
  { city: "Chaumala", rate: 240 },
  { city: "Chautara", rate: 240 },
  { city: "DailekhBazar", rate: 240 },
  { city: "Daman", rate: 240 },
  { city: "Dasdhunga", rate: 240 },
  { city: "Dolalghat", rate: 240 },
  { city: "Gajuri", rate: 235 },
  { city: "Galchi", rate: 240 },
  { city: "GetaKailali", rate: 240 },
  { city: "BardiyaJayanagar", rate: 240 },
  { city: "KailaliJoshipur", rate: 240 },
  { city: "KailaliJugeda", rate: 240 },
  { city: "Khurkot", rate: 240 },
  { city: "KolhabiBazar", rate: 200 },
  { city: "Liwang", rate: 240 },
  { city: "BardiyaMainapokhari", rate: 240 },
  { city: "Manahari", rate: 240 },
  { city: "Masuriya", rate: 240 },
  { city: "Meghauli", rate: 240 },
  { city: "Melamchi", rate: 240 },
  { city: "Naubise", rate: 240 },
  { city: "KushmaNayapul", rate: 230 },
  { city: "DhankutaPakhribas", rate: 210 },
  { city: "Pashupatinagar", rate: 240 },
  { city: "KailaliPhulbari", rate: 240 },
  { city: "Pyuthan", rate: 240 },
  { city: "UdayapurRampur", rate: 240 },
  { city: "Samshergunj", rate: 220 },
  { city: "SattiBazar", rate: 240 },
  { city: "Shantipur", rate: 210 },
  { city: "ShreenagarSalyan", rate: 240 },
  { city: "Sulichaur", rate: 240 },
  { city: "BardiyaTaratal", rate: 240 },
  { city: "Hile", rate: 230 },
  { city: "Amargadhi", rate: 265 },
  { city: "Bhingri", rate: 265 },
  { city: "Bhojpur", rate: 265 },
  { city: "Dhunche", rate: 265 },
  { city: "DipayalBazar", rate: 265 },
  { city: "Garuda", rate: 265 },
  { city: "Mehelkuna", rate: 265 },
  { city: "Musikot", rate: 265 },
  { city: "PyuthanKhalanga", rate: 265 },
  { city: "Silgadhi", rate: 265 },
  { city: "Taplejung", rate: 275 },
  { city: "AchhamSanfebagar", rate: 285 },
  { city: "Mangalsen", rate: 285 },
  { city: "TerathumBasantapur", rate: 290 },
  { city: "DotiBudor", rate: 290 },
  { city: "BhajangChainpur", rate: 290 },
  { city: "ChainpurSankhuwasava", rate: 290 },
  { city: "Chame", rate: 290 },
  { city: "DarchulaKhalanga", rate: 290 },
  { city: "MyagdiDarwang", rate: 290 },
  { city: "Diktel", rate: 290 },
  { city: "Dingla", rate: 290 },
  { city: "Duipiple", rate: 290 },
  { city: "Dullu", rate: 290 },
  { city: "Dunai", rate: 290 },
  { city: "Gokuleshwor", rate: 290 },
  { city: "BaitadiGothalapani", rate: 290 },
  { city: "Jajarkot", rate: 290 },
  { city: "TerhathumJirikhimti", rate: 290 },
  { city: "Jomsom", rate: 290 },
  { city: "Jumla", rate: 290 },
  { city: "JumlaKhalanga", rate: 290 },
  { city: "AchhamKamalBazar", rate: 290 },
  { city: "Khandbari", rate: 290 },
  { city: "Khotang", rate: 290 },
  { city: "Kolti", rate: 290 },
  { city: "Manma", rate: 290 },
  { city: "Martadi", rate: 290 },
  { city: "MuguGamgadhi", rate: 290 },
  { city: "MyanglungBazar", rate: 290 },
  { city: "Okhaldhunga", rate: 290 },
  { city: "BaitadiPatan", rate: 290 },
  { city: "RukumChaurjahari", rate: 290 },
  { city: "Rukumkot", rate: 290 },
  { city: "Salleri", rate: 290 },
  { city: "DhankutaSidhuwa", rate: 290 },
  { city: "Simikot", rate: 290 },
  { city: "TinglaSolu", rate: 290 },
  { city: "Tumlingtar", rate: 290 }
];

// Shipping
export const SHIPPINGFAQS = [
  {
    id: "item-1",
    question: "Order Processing",
    answer: "Orders are processed within 1 business day after payment confirmation. Orders placed on weekends or public holidays will be processed on the next business day."
  },
  {
    id: "item-2",
    question: "Shipping Time",
    answer: "Inside valley: 1-2 business days. Outside valley: 2-3 business days. Delivery times may vary depending on location, courier services, or unforeseen delays. "
  },
  {
    id: "item-3",
    question: "Shipping Charges",
    answer: "Shipping charges are calculated at checkout based on order size and destination. Free shipping may be offered during special promotions."
  },
  {
    id: "item-4",
    question: "Order Tracking",
    answer: "Once your order has been dispatched, a tracking number will be provided if asked by customers."
  },
];
// return
export const RETURNFAQS = [
  {
    id: "return-1",
    question: "Returns",
    answer: "Returns are accepted within 24 hours days of receiving the product. Items must be unused, unwashed, and in original condition, with tags and packaging intact."
  },
  {
    id: "return-2",
    question: "Non-Returnable Items",
    answer: "Discounted or sale items. Gift cards. Customized or made-to-order products"
  },
  {
    id: "return-3",
    question: "Refunds",
    answer: "After we receive and inspect the returned item, we will notify you of the approval status. Approved refunds will be processed to the original payment method within 5–7 business days."
  },
  {
    id: "return-4",
    question: "Exchanges",
    answer: "Exchanges are only applicable for damaged or defective items. Please notify us within 24 hours of delivery with clear photos or videos."


  },
  {
    id: "return-5",
    question: "Return Shipping",
    answer: "Customers are responsible for return shipping costs unless the item received was damaged or incorrect."
  }
];
// FAQS
export const FAQS = [
  {
    id: "faq-1",
    question: "How long does delivery take?",
    answer: "Inside Kathmandu Valley, we deliver within 24-48 hours. For outside valley orders, it typically takes 3-5 business days depending on your location."
  },
  {
    id: "faq-2",
    question: "How do I know my size?",
    answer: "Our fits are generally 'Streetwear Oversized.' We recommend checking the Size Chart on the product page or ordering your standard size for that relaxed look. If you're between sizes, size down for a more standard fit."
  },
  {
    id: "faq-3",
    question: "Do you offer Cash on Delivery (COD)?",
    answer: "Yes, we offer COD nationwide. However, for high-value orders or certain remote locations, our team might reach out for a small commitment advance via eSewa/Khalti."
  },
  {
    id: "faq-4",
    question: "Can I return an item if it doesn't fit?",
    answer: "Absolutely. We have a 7-day exchange policy. The item must be unworn with all Zylo tags attached. Note that the customer handles the return shipping costs for size exchanges."
  },
  {
    id: "faq-5",
    question: "Are your drops limited edition?",
    answer: "Most of our seasonal collections are 'One-Time Drops.' Once a specific design is sold out, we rarely restock it to maintain the exclusivity of the piece."
  },
  {
    id: "faq-6",
    question: "How should I wash my Zylo gear?",
    answer: "To preserve the print and fabric quality, we recommend washing inside out in cold water and hanging to dry. Avoid direct sunlight and never iron directly over the graphics."
  }
];